
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const fortune500 = [
  { "name": "Walmart", "domain": "walmart.com" },
  { "name": "Amazon", "domain": "amazon.com" },
  { "name": "Apple", "domain": "apple.com" },
  { "name": "UnitedHealth Group", "domain": "unitedhealthgroup.com" },
  { "name": "Berkshire Hathaway", "domain": "berkshirehathaway.com" },
  { "name": "CVS Health", "domain": "cvshealth.com" },
  { "name": "Exxon Mobil", "domain": "exxonmobil.com" },
  { "name": "Alphabet", "domain": "abc.xyz" },
  { "name": "McKesson", "domain": "mckesson.com" },
  { "name": "Cencora", "domain": "cencora.com" },
  { "name": "Costco Wholesale", "domain": "costco.com" },
  { "name": "JPMorgan Chase", "domain": "jpmorganchase.com" },
  { "name": "Microsoft", "domain": "microsoft.com" },
  { "name": "Cardinal Health", "domain": "cardinalhealth.com" },
  { "name": "Chevron", "domain": "chevron.com" },
  { "name": "Cigna Group", "domain": "thecignagroup.com" },
  { "name": "Ford Motor", "domain": "ford.com" },
  { "name": "Bank of America", "domain": "bankofamerica.com" },
  { "name": "General Motors", "domain": "gm.com" },
  { "name": "Elevance Health", "domain": "elevancehealth.com" },
  { "name": "Citigroup", "domain": "citigroup.com" },
  { "name": "Centene", "domain": "centene.com" },
  { "name": "Home Depot", "domain": "homedepot.com" },
  { "name": "Marathon Petroleum", "domain": "marathonpetroleum.com" },
  { "name": "Kroger", "domain": "thekrogerco.com" },
  { "name": "Phillips 66", "domain": "phillips66.com" },
  { "name": "Fannie Mae", "domain": "fanniemae.com" },
  { "name": "Walgreens Boots Alliance", "domain": "walgreensbootsalliance.com" },
  { "name": "Valero Energy", "domain": "valero.com" },
  { "name": "Meta Platforms", "domain": "fb.com" },
  { "name": "Verizon Communications", "domain": "verizon.com" },
  { "name": "AT&T", "domain": "att.com" },
  { "name": "Comcast", "domain": "comcastcorporation.com" },
  { "name": "Wells Fargo", "domain": "wellsfargo.com" },
  { "name": "Goldman Sachs Group", "domain": "goldmansachs.com" },
  { "name": "Freddie Mac", "domain": "freddiemac.com" },
  { "name": "Target", "domain": "target.com" },
  { "name": "Humana", "domain": "humana.com" },
  { "name": "State Farm Insurance", "domain": "statefarm.com" },
  { "name": "Tesla", "domain": "tesla.com" },
  { "name": "Morgan Stanley", "domain": "morganstanley.com" },
  { "name": "Johnson & Johnson", "domain": "jnj.com" },
  { "name": "Archer Daniels Midland", "domain": "adm.com" },
  { "name": "PepsiCo", "domain": "pepsico.com" },
  { "name": "UPS", "domain": "ups.com" },
  { "name": "FedEx", "domain": "fedex.com" },
  { "name": "Walt Disney", "domain": "thewaltdisneycompany.com" },
  { "name": "Dell Technologies", "domain": "delltechnologies.com" },
  { "name": "Lowe's", "domain": "lowes.com" },
  { "name": "Procter & Gamble", "domain": "pginvestor.com" },
  { "name": "Energy Transfer", "domain": "energytransfer.com" },
  { "name": "Boeing", "domain": "boeing.com" },
  { "name": "Albertsons", "domain": "albertsonscompanies.com" },
  { "name": "Sysco", "domain": "sysco.com" },
  { "name": "RTX", "domain": "rtx.com" },
  { "name": "General Electric", "domain": "ge.com" },
  { "name": "Lockheed Martin", "domain": "lockheedmartin.com" },
  { "name": "American Express", "domain": "americanexpress.com" },
  { "name": "Caterpillar", "domain": "caterpillar.com" },
  { "name": "MetLife", "domain": "metlife.com" },
  { "name": "HCA Healthcare", "domain": "hcahealthcare.com" },
  { "name": "Progressive", "domain": "progressive.com" },
  { "name": "IBM", "domain": "ibm.com" },
  { "name": "Deere", "domain": "deere.com" },
  { "name": "Nvidia", "domain": "nvidia.com" },
  { "name": "StoneX Group", "domain": "stonex.com" },
  { "name": "Merck", "domain": "merck.com" },
  { "name": "ConocoPhillips", "domain": "conocophillips.com" },
  { "name": "Pfizer", "domain": "pfizer.com" },
  { "name": "Delta Air Lines", "domain": "delta.com" },
  { "name": "TD Synnex", "domain": "tdsynnex.com" },
  { "name": "Publix Super Markets", "domain": "publix.com" },
  { "name": "Allstate", "domain": "allstate.com" },
  { "name": "Cisco Systems", "domain": "cisco.com" },
  { "name": "Nationwide", "domain": "nationwide.com" },
  { "name": "Charter Communications", "domain": "charter.com" },
  { "name": "AbbVie", "domain": "abbvie.com" },
  { "name": "New York Life Insurance", "domain": "newyorklife.com" },
  { "name": "Intel", "domain": "intel.com" },
  { "name": "TJX", "domain": "tjx.com" },
  { "name": "Prudential Financial", "domain": "prudential.com" },
  { "name": "HP", "domain": "hp.com" },
  { "name": "United Airlines Holdings", "domain": "united.com" },
  { "name": "Performance Food Group", "domain": "pfgc.com" },
  { "name": "Tyson Foods", "domain": "tysonfoods.com" },
  { "name": "American Airlines Group", "domain": "aa.com" },
  { "name": "Liberty Mutual Insurance Group", "domain": "libertymutual.com" },
  { "name": "Nike", "domain": "nike.com" },
  { "name": "Oracle", "domain": "oracle.com" },
  { "name": "Enterprise Products Partners", "domain": "enterpriseproducts.com" },
  { "name": "Capital One Financial", "domain": "capitalone.com" },
  { "name": "Plains GP Holdings", "domain": "plains.com" },
  { "name": "World Kinect", "domain": "world-kinect.com" },
  { "name": "AIG", "domain": "aig.com" },
  { "name": "Coca-Cola", "domain": "coca-colacompany.com" },
  { "name": "TIAA", "domain": "tiaa.org" },
  { "name": "CHS", "domain": "chsinc.com" },
  { "name": "Bristol-Myers Squibb", "domain": "bms.com" },
  { "name": "Dow", "domain": "dow.com" },
  { "name": "Best Buy", "domain": "bestbuy.com" },
  { "name": "Thermo Fisher Scientific", "domain": "thermofisher.com" },
  { "name": "Massachusetts Mutual Life Insurance", "domain": "massmutual.com" },
  { "name": "USAA", "domain": "usaa.com" },
  { "name": "General Dynamics", "domain": "gd.com" },
  { "name": "Travelers", "domain": "travelers.com" },
  { "name": "Warner Bros. Discovery", "domain": "wbd.com" },
  { "name": "U.S. Bancorp", "domain": "usbank.com" },
  { "name": "Abbott Laboratories", "domain": "abbott.com" },
  { "name": "Northrop Grumman", "domain": "northropgrumman.com" },
  { "name": "Northwestern Mutual", "domain": "northwesternmutual.com" },
  { "name": "Dollar General", "domain": "dollargeneral.com" },
  { "name": "PBF Energy", "domain": "pbfenergy.com" },
  { "name": "Uber Technologies", "domain": "uber.com" },
  { "name": "Honeywell International", "domain": "honeywell.com" },
  { "name": "Mondelez International", "domain": "mondelezinternational.com" },
  { "name": "Starbucks", "domain": "starbucks.com" },
  { "name": "Qualcomm", "domain": "qualcomm.com" },
  { "name": "Broadcom", "domain": "broadcom.com" },
  { "name": "US Foods Holding", "domain": "usfoods.com" },
  { "name": "D.R. Horton", "domain": "drhorton.com" },
  { "name": "Philip Morris International", "domain": "pmi.com" },
  { "name": "Paccar", "domain": "paccar.com" },
  { "name": "Salesforce", "domain": "salesforce.com" },
  { "name": "Nucor", "domain": "nucor.com" },
  { "name": "Jabil", "domain": "jabil.com" },
  { "name": "Lennar", "domain": "lennar.com" },
  { "name": "Eli Lilly", "domain": "lilly.com" },
  { "name": "Molina Healthcare", "domain": "molinahealthcare.com" },
  { "name": "Cummins", "domain": "cummins.com" },
  { "name": "Bank of New York Mellon", "domain": "bnymellon.com" },
  { "name": "Netflix", "domain": "netflix.com" },
  { "name": "Truist Financial", "domain": "truist.com" },
  { "name": "Arrow Electronics", "domain": "arrow.com" },
  { "name": "3M", "domain": "3m.com" },
  { "name": "Visa", "domain": "visa.com" },
  { "name": "Apollo Global Management", "domain": "apollo.com" },
  { "name": "HF Sinclair", "domain": "hfsinclair.com" },
  { "name": "CBRE Group", "domain": "cbre.com" },
  { "name": "PNC Financial Services Group", "domain": "pnc.com" },
  { "name": "Lithia Motors", "domain": "lithiadriveway.com" },
  { "name": "CarMax", "domain": "carmax.com" },
  { "name": "Paramount Global", "domain": "paramount.com" },
  { "name": "Dollar Tree", "domain": "dollartree.com" },
  { "name": "United Natural Foods", "domain": "unfi.com" },
  { "name": "PayPal Holdings", "domain": "paypal.com" },
  { "name": "Penske Automotive Group", "domain": "penskeautomotive.com" },
  { "name": "Hewlett Packard Enterprise", "domain": "hpe.com" },
  { "name": "Duke Energy", "domain": "duke-energy.com" },
  { "name": "Occidental Petroleum", "domain": "oxy.com" },
  { "name": "NRG Energy", "domain": "nrg.com" },
  { "name": "Amgen", "domain": "amgen.com" },
  { "name": "NextEra Energy", "domain": "nexteraenergy.com" },
  { "name": "Danaher", "domain": "danaher.com" },
  { "name": "Gilead Sciences", "domain": "gilead.com" },
  { "name": "AutoNation", "domain": "autonation.com" },
  { "name": "Kraft Heinz", "domain": "kraftheinzcompany.com" },
  { "name": "Avnet", "domain": "avnet.com" },
  { "name": "Applied Materials", "domain": "appliedmaterials.com" },
  { "name": "Southwest Airlines", "domain": "southwest.com" },
  { "name": "Charles Schwab", "domain": "aboutschwab.com" },
  { "name": "Baker Hughes", "domain": "bakerhughes.com" },
  { "name": "McDonald's", "domain": "mcdonalds.com" },
  { "name": "Southern", "domain": "southerncompany.com" },
  { "name": "Mastercard", "domain": "mastercard.com" },
  { "name": "Constellation Energy", "domain": "constellationenergy.com" },
  { "name": "Hartford Financial Services Group", "domain": "thehartford.com" },
  { "name": "PG&E", "domain": "pgecorp.com" },
  { "name": "Coupang", "domain": "aboutcoupang.com" },
  { "name": "EOG Resources", "domain": "eogresources.com" },
  { "name": "Union Pacific", "domain": "up.com" },
  { "name": "Rite Aid", "domain": "riteaid.com" },
  { "name": "Macy's", "domain": "macysinc.com" },
  { "name": "Marriott International", "domain": "marriott.com" },
  { "name": "Lear", "domain": "lear.com" },
  { "name": "Genuine Parts", "domain": "genpt.com" },
  { "name": "Sherwin-Williams", "domain": "sherwin.com" },
  { "name": "Halliburton", "domain": "halliburton.com" },
  { "name": "Freeport-McMoRan", "domain": "fcx.com" },
  { "name": "Live Nation Entertainment", "domain": "livenationentertainment.com" },
  { "name": "Marsh & McLennan", "domain": "marshmclennan.com" },
  { "name": "Advanced Micro Devices", "domain": "amd.com" },
  { "name": "First Citizens BancShares", "domain": "firstcitizens.com" },
  { "name": "WESCO International", "domain": "wesco.com" },
  { "name": "Carrier Global", "domain": "carrier.com" },
  { "name": "Cleveland-Cliffs", "domain": "clevelandcliffs.com" },
  { "name": "Block", "domain": "block.xyz" },
  { "name": "Exelon", "domain": "exeloncorp.com" },
  { "name": "KKR", "domain": "kkr.com" },
  { "name": "CDW", "domain": "cdw.com" },
  { "name": "Booking Holdings", "domain": "bookingholdings.com" },
  { "name": "Synchrony", "domain": "synchrony.com" },
  { "name": "Quanta Services", "domain": "quantaservices.com" },
  { "name": "Jones Lang LaSalle", "domain": "jll.com" },
  { "name": "Discover Financial Services", "domain": "discover.com" },
  { "name": "Tenet Healthcare", "domain": "tenethealth.com" },
  { "name": "Altria Group", "domain": "altria.com" },
  { "name": "Stryker", "domain": "stryker.com" },
  { "name": "Kimberly-Clark", "domain": "kimberly-clark.com" },
  { "name": "Waste Management", "domain": "wm.com" },
  { "name": "Cheniere Energy", "domain": "cheniere.com" },
  { "name": "Ross Stores", "domain": "rossstores.com" },
  { "name": "WestRock", "domain": "westrock.com" },
  { "name": "General Mills", "domain": "generalmills.com" },
  { "name": "Goodyear Tire & Rubber", "domain": "goodyear.com" },
  { "name": "BJ's Wholesale Club", "domain": "bjs.com" },
  { "name": "GE HealthCare Technologies", "domain": "gehealthcare.com" },
  { "name": "Colgate-Palmolive", "domain": "colgatepalmolive.com" },
  { "name": "Whirlpool", "domain": "whirlpoolcorp.com" },
  { "name": "L3Harris Technologies", "domain": "l3harris.com" },
  { "name": "Adobe", "domain": "adobe.com" },
  { "name": "Becton Dickinson", "domain": "bd.com" },
  { "name": "Pioneer Natural Resources", "domain": "pxd.com" },
  { "name": "Cognizant Technology Solutions", "domain": "cognizant.com" },
  { "name": "Murphy USA", "domain": "murphyusa.com" },
  { "name": "Fiserv", "domain": "fiserv.com" },
  { "name": "Parker-Hannifin", "domain": "phstock.com" },
  { "name": "American Electric Power", "domain": "aep.com" },
  { "name": "International Paper", "domain": "internationalpaper.com" },
  { "name": "ManpowerGroup", "domain": "manpowergroup.com" },
  { "name": "Aramark", "domain": "aramark.com" },
  { "name": "Steel Dynamics", "domain": "steeldynamics.com" },
  { "name": "Aflac", "domain": "aflac.com" },
  { "name": "Reinsurance Group of America", "domain": "rgare.com" },
  { "name": "Emerson Electric", "domain": "emerson.com" },
  { "name": "State Street", "domain": "statestreet.com" },
  { "name": "PPG Industries", "domain": "ppg.com" },
  { "name": "United States Steel", "domain": "ussteel.com" },
  { "name": "Automatic Data Processing", "domain": "adp.com" },
  { "name": "Group 1 Automotive", "domain": "group1auto.com" },
  { "name": "Dominion Energy", "domain": "dominionenergy.com" },
  { "name": "BlackRock", "domain": "blackrock.com" },
  { "name": "Oneok", "domain": "oneok.com" },
  { "name": "C.H. Robinson Worldwide", "domain": "chrobinson.com" },
  { "name": "Texas Instruments", "domain": "ti.com" },
  { "name": "Kohl's", "domain": "kohls.com" },
  { "name": "AutoZone", "domain": "autozone.com" },
  { "name": "Lam Research", "domain": "lamresearch.com" },
  { "name": "Corteva", "domain": "corteva.com" },
  { "name": "Peter Kiewit Sons'", "domain": "kiewit.com" },
  { "name": "Builders FirstSource", "domain": "bldr.com" },
  { "name": "Kyndryl Holdings", "domain": "kyndryl.com" },
  { "name": "EchoStar", "domain": "echostar.com" },
  { "name": "American Family Insurance Group", "domain": "amfam.com" },
  { "name": "Delek US Holdings", "domain": "delekus.com" },
  { "name": "Land O'Lakes", "domain": "landolakesinc.com" },
  { "name": "Sempra", "domain": "sempra.com" },
  { "name": "Global Partners", "domain": "globalp.com" },
  { "name": "Grainger", "domain": "grainger.com" },
  { "name": "Jacobs Solutions", "domain": "jacobs.com" },
  { "name": "Edison International", "domain": "edisoninvestor.com" },
  { "name": "MGM Resorts International", "domain": "mgmresorts.com" },
  { "name": "Guardian Life Ins. Co. of America", "domain": "guardianlife.com" },
  { "name": "Illinois Tool Works", "domain": "itw.com" },
  { "name": "Ameriprise Financial", "domain": "ameriprise.com" },
  { "name": "PulteGroup", "domain": "pultegroupinc.com" },
  { "name": "Targa Resources", "domain": "targaresources.com" },
  { "name": "Ally Financial", "domain": "ally.com" },
  { "name": "BorgWarner", "domain": "borgwarner.com" },
  { "name": "Est?e Lauder", "domain": "elcompanies.com" },
  { "name": "Loews", "domain": "loews.com" },
  { "name": "O'Reilly Automotive", "domain": "oreillyauto.com" },
  { "name": "Markel Group", "domain": "mklgroup.com" },
  { "name": "Stanley Black & Decker", "domain": "stanleyblackanddecker.com" },
  { "name": "Micron Technology", "domain": "micron.com" },
  { "name": "Fluor", "domain": "fluor.com" },
  { "name": "Leidos Holdings", "domain": "leidos.com" },
  { "name": "Viatris", "domain": "viatris.com" },
  { "name": "Kinder Morgan", "domain": "kindermorgan.com" },
  { "name": "Ecolab", "domain": "ecolab.com" },
  { "name": "Baxter International", "domain": "baxter.com" },
  { "name": "Devon Energy", "domain": "devonenergy.com" },
  { "name": "Kellanova", "domain": "kellanova.com" },
  { "name": "Farmers Insurance Exchange", "domain": "farmers.com" },
  { "name": "Casey's General Stores", "domain": "caseys.com" },
  { "name": "IQVIA Holdings", "domain": "iqvia.com" },
  { "name": "Republic Services", "domain": "republicservices.com" },
  { "name": "Fox", "domain": "foxcorporation.com" },
  { "name": "Gap", "domain": "gapinc.com" },
  { "name": "Keurig Dr Pepper", "domain": "keurig.com" },
  { "name": "Reliance", "domain": "reliance.com" },
  { "name": "Asbury Automotive Group", "domain": "asburyauto.com" },
  { "name": "Pacific Life", "domain": "pacificlife.com" },
  { "name": "Vistra", "domain": "vistracorp.com" },
  { "name": "Western & Southern Financial Group", "domain": "westernsouthern.com" },
  { "name": "Andersons", "domain": "andersonsinc.com" },
  { "name": "Nordstrom", "domain": "nordstrom.com" },
  { "name": "Omnicom Group", "domain": "omnicomgroup.com" },
  { "name": "Fidelity National Information Services", "domain": "fisglobal.com" },
  { "name": "Consolidated Edison", "domain": "conedison.com" },
  { "name": "CSX", "domain": "csx.com" },
  { "name": "AECOM", "domain": "aecom.com" },
  { "name": "Lumen Technologies", "domain": "lumen.com" },
  { "name": "Tractor Supply", "domain": "tractorsupply.com" },
  { "name": "DXC Technology", "domain": "dxc.technology" },
  { "name": "AGCO", "domain": "agcocorp.com" },
  { "name": "Sonic Automotive", "domain": "sonicautomotive.com" },
  { "name": "Intuit", "domain": "intuit.com" },
  { "name": "United Rentals", "domain": "unitedrentals.com" },
  { "name": "Universal Health Services", "domain": "uhs.com" },
  { "name": "Boston Scientific", "domain": "bostonscientific.com" },
  { "name": "Otis Worldwide", "domain": "otis.com" },
  { "name": "Xcel Energy", "domain": "xcelenergy.com" },
  { "name": "Edward Jones", "domain": "edwardjones.com" },
  { "name": "Ball", "domain": "ball.com" },
  { "name": "LKQ", "domain": "lkqcorp.com" },
  { "name": "Mutual of Omaha", "domain": "mutualofomaha.com" },
  { "name": "Mosaic", "domain": "mosaicco.com" },
  { "name": "Textron", "domain": "textron.com" },
  { "name": "Laboratory Corp. of America", "domain": "labcorp.com" },
  { "name": "Principal Financial", "domain": "principal.com" },
  { "name": "Regeneron Pharmaceuticals", "domain": "regeneron.com" },
  { "name": "Raymond James Financial", "domain": "raymondjames.com" },
  { "name": "Dick's Sporting Goods", "domain": "dickssportinggoods.com" },
  { "name": "Auto-Owners Insurance", "domain": "auto-owners.com" },
  { "name": "Expedia Group", "domain": "expediagroup.com" },
  { "name": "J.B. Hunt Transport Services", "domain": "jbhunt.com" },
  { "name": "M&T Bank", "domain": "mtb.com" },
  { "name": "DTE Energy", "domain": "dteenergy.com" },
  { "name": "AES", "domain": "aes.com" },
  { "name": "Berry Global Group", "domain": "berryglobal.com" },
  { "name": "Fifth Third Bancorp", "domain": "53.com" },
  { "name": "Air Products & Chemicals", "domain": "airproducts.com" },
  { "name": "Corning", "domain": "corning.com" },
  { "name": "EMCOR Group", "domain": "emcorgroup.com" },
  { "name": "Amphenol", "domain": "amphenol.com" },
  { "name": "Westlake", "domain": "westlake.com" },
  { "name": "DuPont", "domain": "dupont.com" },
  { "name": "Liberty Media", "domain": "libertymedia.com" },
  { "name": "S&P Global", "domain": "spglobal.com" },
  { "name": "Community Health Systems", "domain": "chs.net" },
  { "name": "FirstEnergy", "domain": "firstenergycorp.com" },
  { "name": "Unum Group", "domain": "unum.com" },
  { "name": "Henry Schein", "domain": "henryschein.com" },
  { "name": "Western Digital", "domain": "westerndigital.com" },
  { "name": "Analog Devices", "domain": "analog.com" },
  { "name": "Conagra Brands", "domain": "conagrabrands.com" },
  { "name": "Citizens Financial Group", "domain": "citizensbank.com" },
  { "name": "Norfolk Southern", "domain": "norfolksouthern.com" },
  { "name": "Entergy", "domain": "entergy.com" },
  { "name": "W.R. Berkley", "domain": "berkley.com" },
  { "name": "DaVita", "domain": "davita.com" },
  { "name": "Northern Trust", "domain": "northerntrust.com" },
  { "name": "Hormel Foods", "domain": "hormelfoods.com" },
  { "name": "Crown Holdings", "domain": "crowncork.com" },
  { "name": "Avis Budget Group", "domain": "avisbudgetgroup.com" },
  { "name": "Wayfair", "domain": "wayfair.com" },
  { "name": "MasTec", "domain": "mastec.com" },
  { "name": "Eversource Energy", "domain": "eversource.com" },
  { "name": "Newmont", "domain": "newmont.com" },
  { "name": "Ryder System", "domain": "ryder.com" },
  { "name": "Fidelity National Financial", "domain": "fnf.com" },
  { "name": "Molson Coors Beverage", "domain": "molsoncoors.com" },
  { "name": "Caesars Entertainment", "domain": "caesars.com" },
  { "name": "Lincoln National", "domain": "lincolnfinancial.com" },
  { "name": "VF", "domain": "vfc.com" },
  { "name": "International Flavors & Fragrances", "domain": "iff.com" },
  { "name": "Huntington Ingalls Industries", "domain": "hii.com" },
  { "name": "Advance Auto Parts", "domain": "advanceautoparts.com" },
  { "name": "Public Service Enterprise Group", "domain": "pseg.com" },
  { "name": "Ulta Beauty", "domain": "ulta.com" },
  { "name": "Hershey", "domain": "thehersheycompany.com" },
  { "name": "Chewy", "domain": "chewy.com" },
  { "name": "American Tower", "domain": "americantower.com" },
  { "name": "Mohawk Industries", "domain": "mohawkind.com" },
  { "name": "Assurant", "domain": "assurant.com" },
  { "name": "Thor Industries", "domain": "thorindustries.com" },
  { "name": "Graybar Electric", "domain": "graybar.com" },
  { "name": "Yum China Holdings", "domain": "yumchina.com" },
  { "name": "Celanese", "domain": "celanese.com" },
  { "name": "Qurate Retail", "domain": "qurateretail.com" },
  { "name": "Williams", "domain": "williams.com" },
  { "name": "Interpublic Group", "domain": "interpublic.com" },
  { "name": "Ovintiv", "domain": "ovintiv.com" },
  { "name": "Icahn Enterprises", "domain": "ielp.com" },
  { "name": "Huntington Bancshares", "domain": "huntington.com" },
  { "name": "Erie Insurance Group", "domain": "erieinsurance.com" },
  { "name": "Carvana", "domain": "carvana.com" },
  { "name": "Hess", "domain": "hess.com" },
  { "name": "Dana", "domain": "dana.com" },
  { "name": "Alcoa", "domain": "alcoa.com" },
  { "name": "Equitable Holdings", "domain": "equitableholdings.com" },
  { "name": "KLA", "domain": "kla.com" },
  { "name": "Darden Restaurants", "domain": "darden.com" },
  { "name": "Autoliv", "domain": "autoliv.com" },
  { "name": "Alaska Air Group", "domain": "alaskaair.com" },
  { "name": "KeyCorp", "domain": "key.com" },
  { "name": "Las Vegas Sands", "domain": "sands.com" },
  { "name": "Owens & Minor", "domain": "owens-minor.com" },
  { "name": "Hilton Worldwide Holdings", "domain": "hilton.com" },
  { "name": "Ebay", "domain": "ebay.com" },
  { "name": "Arthur J. Gallagher", "domain": "ajg.com" },
  { "name": "LPL Financial Holdings", "domain": "lpl.com" },
  { "name": "Cincinnati Financial", "domain": "cinfin.com" },
  { "name": "Toll Brothers", "domain": "tollbrothers.com" },
  { "name": "Motorola Solutions", "domain": "motorolasolutions.com" },
  { "name": "Airbnb", "domain": "airbnb.com" },
  { "name": "Intercontinental Exchange", "domain": "ice.com" },
  { "name": "News Corp.", "domain": "newscorp.com" },
  { "name": "Chipotle Mexican Grill", "domain": "chipotle.com" },
  { "name": "Vertex Pharmaceuticals", "domain": "vrtx.com" },
  { "name": "Biogen", "domain": "biogen.com" },
  { "name": "GXO Logistics", "domain": "gxo.com" },
  { "name": "SpartanNash", "domain": "spartannash.com" },
  { "name": "Burlington Stores", "domain": "burlingtoninvestors.com" },
  { "name": "Thrivent Financial for Lutherans", "domain": "thrivent.com" },
  { "name": "NVR", "domain": "nvrinc.com" },
  { "name": "Owens Corning", "domain": "owenscorning.com" },
  { "name": "Westinghouse Air Brake Technologies", "domain": "wabteccorp.com" },
  { "name": "Oshkosh", "domain": "oshkoshcorp.com" },
  { "name": "Global Payments", "domain": "globalpaymentsinc.com" },
  { "name": "Lululemon athletica", "domain": "lululemon.com" },
  { "name": "Albemarle", "domain": "albemarle.com" },
  { "name": "JetBlue Airways", "domain": "jetblue.com" },
  { "name": "Seaboard", "domain": "seaboardcorp.com" },
  { "name": "Constellation Brands", "domain": "cbrands.com" },
  { "name": "Graphic Packaging Holding", "domain": "graphicpkg.com" },
  { "name": "Hertz Global Holdings", "domain": "hertz.com" },
  { "name": "FM Global", "domain": "fmglobal.com" },
  { "name": "Campbell Soup", "domain": "campbellsoupcompany.com" },
  { "name": "Expeditors Intl. of Washington", "domain": "expeditors.com" },
  { "name": "A-Mark Precious Metals", "domain": "amark.com" },
  { "name": "Booz Allen Hamilton Holding", "domain": "boozallen.com" },
  { "name": "Quest Diagnostics", "domain": "questdiagnostics.com" },
  { "name": "Altice USA", "domain": "alticeusa.com" },
  { "name": "PVH", "domain": "pvh.com" },
  { "name": "Eastman Chemical", "domain": "eastman.com" },
  { "name": "Insight Enterprises", "domain": "insight.com" },
  { "name": "Regions Financial", "domain": "regions.com" },
  { "name": "Beacon Roofing Supply", "domain": "becn.com" },
  { "name": "Rockwell Automation", "domain": "rockwellautomation.com" },
  { "name": "Polaris", "domain": "polaris.com" },
  { "name": "ServiceNow", "domain": "servicenow.com" },
  { "name": "Sanmina", "domain": "sanmina.com" },
  { "name": "UGI", "domain": "ugicorp.com" },
  { "name": "WEC Energy Group", "domain": "wecenergygroup.com" },
  { "name": "BrightSpring Health Services", "domain": "brightspringhealth.com" },
  { "name": "Cintas", "domain": "cintas.com" },
  { "name": "Commercial Metals", "domain": "cmc.com" },
  { "name": "Continental Resources", "domain": "clr.com" },
  { "name": "Chesapeake Energy", "domain": "chk.com" },
  { "name": "CenterPoint Energy", "domain": "centerpointenergy.com" },
  { "name": "NGL Energy Partners", "domain": "nglenergypartners.com" },
  { "name": "DoorDash", "domain": "doordash.com" },
  { "name": "NOV", "domain": "nov.com" },
  { "name": "Zoetis", "domain": "zoetis.com" },
  { "name": "J.M. Smucker", "domain": "jmsmucker.com" },
  { "name": "Microchip Technology", "domain": "microchip.com" },
  { "name": "Dover", "domain": "dovercorporation.com" },
  { "name": "Diamondback Energy", "domain": "diamondbackenergy.com" },
  { "name": "Avery Dennison", "domain": "averydennison.com" },
  { "name": "PPL", "domain": "pplweb.com" },
  { "name": "ON Semiconductor", "domain": "onsemi.com" },
  { "name": "ARKO", "domain": "arkocorp.com" },
  { "name": "Par Pacific Holdings", "domain": "parpacific.com" },
  { "name": "APA", "domain": "apacorp.com" },
  { "name": "Equinix", "domain": "equinix.com" },
  { "name": "New York Community Bancorp", "domain": "mynycb.com" },
  { "name": "Foot Locker", "domain": "footlocker.comcorp" },
  { "name": "Ingredion", "domain": "ingredion.com" },
  { "name": "Newell Brands", "domain": "newellbrands.com" },
  { "name": "ABM Industries", "domain": "abm.com" },
  { "name": "Securian Financial Group", "domain": "securian.com" },
  { "name": "Prologis", "domain": "prologis.com" },
  { "name": "Blackstone", "domain": "blackstone.com" },
  { "name": "Skechers U.S.A.", "domain": "skechers.com" },
  { "name": "Masco", "domain": "masco.com" },
  { "name": "Rush Enterprises", "domain": "rushenterprises.com" },
  { "name": "Franklin Resources", "domain": "franklinresources.com" },
  { "name": "ODP", "domain": "theodpcorp.com" },
  { "name": "American Financial Group", "domain": "afginc.com" },
  { "name": "Packaging Corp. of America", "domain": "packagingcorp.com" },
  { "name": "Vulcan Materials", "domain": "vulcanmaterials.com" },
  { "name": "Interactive Brokers Group", "domain": "interactivebrokers.com" },
  { "name": "Williams-Sonoma", "domain": "williams-sonomainc.com" },
  { "name": "XPO", "domain": "xpo.com" },
  { "name": "Weyerhaeuser", "domain": "weyerhaeuser.com" },
  { "name": "Genworth Financial", "domain": "genworth.com" },
  { "name": "CMS Energy", "domain": "cmsenergy.com" },
  { "name": "Science Applications International", "domain": "saic.com" },
  { "name": "Jefferies Financial Group", "domain": "jefferies.com" },
  { "name": "Bath & Body Works", "domain": "bbwinc.com" },
  { "name": "Electronic Arts", "domain": "ea.com" },
  { "name": "Taylor Morrison Home", "domain": "taylormorrison.com" },
  { "name": "Zimmer Biomet Holdings", "domain": "zimmerbiomet.com" },
  { "name": "Clorox", "domain": "thecloroxcompany.com" },
  { "name": "Xylem", "domain": "xylem.com" },
  { "name": "Voya Financial", "domain": "voya.com" },
  { "name": "Fastenal", "domain": "fastenal.com" },
  { "name": "Watsco", "domain": "watsco.com" },
  { "name": "Workday", "domain": "workday.com" },
  { "name": "Old Republic International", "domain": "oldrepublic.com" },
  { "name": "RPM International", "domain": "rpminc.com" },
  { "name": "UFP Industries", "domain": "ufpi.com" },
  { "name": "Ameren", "domain": "ameren.com" },
  { "name": "Knight-Swift Transportation Hldgs.", "domain": "knight-swift.com" },
  { "name": "Monster Beverage", "domain": "monsterbevcorp.com" },
  { "name": "Intuitive Surgical", "domain": "intuitive.com" },
  { "name": "Super Micro Computer", "domain": "supermicro.com" },
  { "name": "Concentrix", "domain": "concentrix.com" },
  { "name": "O-I Glass", "domain": "o-i.com" }
];

async function seed() {
    console.log(`Starting seed process for ${fortune500.length} companies...`);
    let addedCount = 0;
    let skippedCount = 0;
    let updatedCount = 0;

    for (const company of fortune500) {
        try {
            const existing = await prisma.company.findUnique({
                where: { name: company.name }
            });

            const logoUrl = `https://img.logo.dev/${company.domain}`;

            if (!existing) {
                await prisma.company.create({
                    data: {
                        name: company.name,
                        domain: company.domain,
                        logoUrl: logoUrl,
                        logoFetched: true
                    }
                });
                addedCount++;
            } else {
                // Update existing company with new logoUrl from logo.dev
                await prisma.company.update({
                    where: { id: existing.id },
                    data: {
                        domain: company.domain,
                        logoUrl: logoUrl,
                        logoFetched: true
                    }
                });
                updatedCount++;
            }
        } catch (error) {
            console.error(`Failed to process ${company.name}:`, error);
        }
    }

    console.log(`Seed complete.`);
    console.log(`Added: ${addedCount}`);
    console.log(`Updated: ${updatedCount}`);
    console.log(`Total processed: ${addedCount + updatedCount}`);
    
    await prisma.$disconnect();
}

seed();
